### ISSUE TITLE
Breaks with Google's Appointment Scheduler

### ISSUE THREAD

**Issue by guitarbeat** [HCAWN/gcal-multical-event-merge#14] opened 2022-08-29 23:08 UTC
To recreate all you need to do is create three different appointment slots. Original plug in does this too. 
<img width="132" alt="Screen Shot 2022-08-29 at 6 08 19 PM" src="https://user-images.githubusercontent.com/83775388/187314180-573b9d3a-0348-46c8-bd15-16481c77636e.png">

**Comment by HCAWN** [comment] 2022-08-30 15:58
![image](https://user-images.githubusercontent.com/40216444/187484531-7264eaa7-f17e-41b2-8935-4fc3a846d2b4.png)
I cannot replicate this. Please share more information

**Comment by guitarbeat** [comment] 2022-08-31 16:13
try name the test appointments differently?

**Comment by HCAWN** [comment] 2022-09-01 08:00
By design, events with different names are not merged as they are not the same event appearing in multiple calendars they are just different events happening at the same time. Unless I misunderstand?

**Comment by guitarbeat** [comment] 2022-09-01 14:52
Correct, yet for some reason the plug in still merges them in this weird waySent from my iPhoneOn Sep 1, 2022, at 3:00 AM, Henry Neilson ***@***.***> wrote:﻿
By design, events with different names are not merged as they are not the same event appearing in multiple calendars they are just different events happening at the same time. Unless I misunderstand?

**Comment by HCAWN** [comment] 2022-09-01 15:37
![image](https://user-images.githubusercontent.com/40216444/187954260-3e800352-0b66-43e7-bfbb-3ac767c75ddb.png)
I have created three appointment slots, in three different calendars with three different names and they do not merge.
Please share more information about how to re-create this?
A screenshot of how the events look with the extension disabled.
- Are they all day events
- What are the event titled
- Are they in the same calendar or three different calendars
- How does it look with just two events? 

H

**Comment by guitarbeat** [comment] 2022-09-01 22:04
<img width="276" alt="image" src="https://user-images.githubusercontent.com/83775388/188019586-34bb0fd3-ded7-4132-942b-130a36128bdc.png">
These are events from 9 am to 5 pm. They are titled, "15 minute meetings", "30 minute meetings" and "1 hour meetings." They are in the same calendar.  The below screenshot shows how they look when the chrom extension is activated. 
<img width="276" alt="image" src="https://user-images.githubusercontent.com/83775388/188020707-ac3964be-3a79-4d2c-a8f9-9017b2e491fd.png">
The below shows how it looks when there is only two events, and the extension is stilled activated. 
<img width="142" alt="image" src="https://user-images.githubusercontent.com/83775388/188020823-912345c3-e68a-4001-b040-7fa0c41829ee.png">
To note, the issue goes away in day view, but it becomes apparent in week view. There also has to be other events in front of them too sometimes. I would play around with that.

**Comment by HCAWN** [comment] 2022-09-02 08:12
I'm sorry I'm still unable to replicate this scenario.
This is with the extension enabled (looks the same disabled)
3 Appointment events with the same respective titles you gave. 9-5. all in the same calendar:
![image](https://user-images.githubusercontent.com/40216444/188094319-a854fd07-dc4a-4a7a-8fe7-e9b4dfb55d7f.png)
Ignoring the extension, I just can't replicate the your first image which was meant to be how the events look "normally". They look nothing like mine and nothing like how normal events look either. Why is the title for only one of the events visible?
As a side - what version number is written top left of the extension popup for you?
H

**Comment by HCAWN** [comment] 2023-04-30 07:56
Closing due to inactivity. I was unable to replicate. Please re-open if new info arises

**Closed by HCAWN** 2023-04-30 07:56 UTC
