### ISSUE TITLE
[BUG] Blank lines between merged events

### ISSUE THREAD

**Issue by celiasmith** [HCAWN/gcal-multical-event-merge#38] opened 2024-09-25 14:11 UTC
**Describe the bug**
Display of merged events has blank lines between them, both in month view and month popup

**To Reproduce**
1. Happens with all merged events
![image](https://github.com/user-attachments/assets/1e72420b-80ad-40f1-9e84-18fa3e51aade)
![image](https://github.com/user-attachments/assets/aabf2604-4f3e-409b-987d-1d815e19f720)

**Expected behaviour**
1. No blank lines between events. This is a functional issue in the month view, as only a few events are shown on days that have many until you click the '5 more' at the bottom.

**Device**
 - OS: MacOS
 - Browser: Chrome
 - Extension Version: 2.3.10

**Comment by HCAWN** [comment] 2024-09-25 22:08
Hi @celiasmith 
I will have a look tomorrow but strongly suspect this is caused by the same thing that partially broke the extension last week:
https://github.com/HCAWN/gcal-multical-event-merge/issues/36
Google changed some of the code in the calendar app. I'll make the fix tomorrow and tag you/this thread as it progresses to being live.

H

**Comment by celiasmith** [comment] 2024-10-15 20:53
Not sure on etiquette for inquiring about a possible fix, but I was wondering if you had a chance to look at this one @HCAWN ?

**Comment by Gubbahubba** [comment] 2024-10-27 21:54
Same here. Looking very much forward to your fix, this would honestly be a gamechanger for me @HCAWN Keep up the good work.

**Comment by HCAWN** [comment] 2024-10-28 15:59
@Gubbahubba & @celiasmith 
https://github.com/HCAWN/gcal-multical-event-merge/pull/40

Have made this fix, it's a very small change to dail with the ongoing changes Google made to their code last month. Will post here when the extension is live and requires a refresh, please let me know if that fixes the issue for you and then I'll close this issue>

H

**Comment by HCAWN** [comment] 2024-10-28 20:21
2.3.11 live now

**Comment by Gubbahubba** [comment] 2024-10-29 08:49
Fantastic, it works! Thank you!

**Comment by celiasmith** [comment] 2024-10-30 17:55
Yup, much better for me too! Thanks. (I do still get 'empty' space in the main calendar view, but this was the case before as well  
![image](https://github.com/user-attachments/assets/5063b7b3-b0eb-4fd1-bf7d-da13cfc53d8b)
)

**Comment by HCAWN** [comment] 2024-10-31 17:17
Resolved, still https://github.com/HCAWN/gcal-multical-event-merge/issues/34

**Closed by HCAWN** 2024-10-31 17:17 UTC
